# Generated by Django 2.1.7 on 2019-04-05 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_reviewed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='reviewed_by',
        ),
    ]
